- name: Copy isample1.txt file and move to the server
  hosts: webservers
  tasks:
    - name: Upload sample1.txt file
      copy:
        src: ./config/sample1.txt
        dest: ./
        mode: 0755
      become: true